version: 2

models:  
  - name: lndg_enterprise_survey
    description: "Model for the Landing Enerprise Survey"
    columns:
        - name: id
          tests:
              - not_null
        - name: year
        - name: industry_code_ANZSIC
        - name: industry_name_ANZSIC
        - name: rme_size_grp
        - name: variable
        - name: value
        - name: unit
        - name: source_file
        - name: created_ts
        - name: created_by
        - name: last_modified_ts
        - name: last_modified_by

  - name: stg_enterprise_survey
    description: "Model for the Staging Enerprise Survey"
    columns:
        - name: id
          tests:
              - not_null
        - name: year
        - name: industry_code_ANZSIC
        - name: industry_name_ANZSIC
        - name: rme_size_grp
        - name: variable
        - name: value
        - name: unit
        - name: source_file
        - name: created_ts
        - name: created_by
        - name: last_modified_ts
        - name: last_modified_by

  - name: enterprise_survey
    description: "Model for the Staging Enerprise Survey"
    columns:
        - name: id
          tests:
              - not_null
        - name: year
        - name: industry_code_ANZSIC
        - name: industry_name_ANZSIC
        - name: rme_size_grp
        - name: variable
        - name: value
        - name: unit
        - name: source_file
        - name: created_ts
        - name: created_by
        - name: last_modified_ts
        - name: last_modified_by

  - name: my_python_model
    description: My transformation written in Python
    config:
      materialized: table
      tags: ['python']

    columns:
      - name: id
        tests:
          - unique
          - not_null
      # - name: email
      #   tests:
      #     - is_email