
# version: 2

# models:
#     - name: test_csv_external
#       description: "A test model"
#       columns:
#           - name: id
#             tests:
#                 - unique
#                 - not_null
#           - name: first_name
#           - name: last_name

#     - name: test_landing
#       description: "A test model"
#       columns:
#           - name: id
#             tests:
#                 - unique
#                 - not_null
#           - name: first_name
#           - name: last_name
#           - name: created_ts

#     - name: test_staging
#       description: "A test model"
#       columns:
#           - name: id
#             tests:
#                 - unique
#                 - not_null
#           - name: first_name
#           - name: last_name
#           - name: created_ts 

#     - name: test_consumption
#       description: "A test model"
#       columns:
#           - name: id
#             tests:
#                 - unique
#                 - not_null
#           - name: first_name
#           - name: last_name
#           - name: created_ts