
version: 2

sources:
  - name: dbt_landing
    database: dm-solutions
    tables:
      # - name: test_csv_external
      #   description: "external table"
      # - name: test_landing
      #   description: "external table"

      - name: ext_enterprise_survey
        description: "The CSV External Table for Enterprise Survey"

  #     - name: lndg_enterprise_survey
  #       description: "The Landing table for the Enterprise Data"

      - name: my-python-model
        description: "The Landing table for the Enterprise Data"
        columns:
          - name: email
            tests:
              - is_email

  # - name: dbt_staging
  #   database: dm-solutions
  #   tables:
  #     - name: test_staging
  #       description: "external table"

  #     - name: stg_enterprise_survey
  #       description: "The Staging table for the Enterprise Data"


  # - name: dbt_consumption
  #   database: dm-solutions
  #   tables:
  #     - name: test_consumption
  #       description: "external table"

  #     - name: enterprise_survey
  #       description: "The Consumption table for the Enterprise Data"

